# Generated by Django 5.0.6 on 2026-06-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClinicInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Dental Clinic", max_length=150)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=60)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="clinic/")),
                ("default_language", models.CharField(default="en", max_length=5)),
                (
                    "default_calendar",
                    models.CharField(
                        choices=[
                            ("gregorian", "Gregorian"),
                            ("solar_hijri", "Solar Hijri"),
                        ],
                        default="gregorian",
                        max_length=12,
                    ),
                ),
                ("currency", models.CharField(default="AFN", max_length=10)),
                ("settings", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Clinic information",
                "verbose_name_plural": "Clinic information",
            },
        ),
    ]
