# Generated by Django 5.0.6 on 2026-06-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicinfo",
            name="appointment_duration_minutes",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="clinicinfo",
            name="invoice_footer",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="clinicinfo",
            name="prescription_footer",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="clinicinfo",
            name="prescription_header",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="clinicinfo",
            name="tax_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clinicinfo",
            name="tax_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="clinicinfo",
            name="website",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="clinicinfo",
            name="working_hours",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="clinicinfo",
            name="default_calendar",
            field=models.CharField(
                choices=[("gregorian", "Gregorian"), ("solar_hijri", "Solar Hijri")],
                default="solar_hijri",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="clinicinfo",
            name="default_language",
            field=models.CharField(default="fa", max_length=5),
        ),
    ]
