# Generated by Django 5.0.6 on 2026-06-01 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("PAYMENT", "Payment"),
                            ("INVOICE", "Invoice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity", models.CharField(blank=True, max_length=60)),
                ("entity_id", models.CharField(blank=True, max_length=40)),
                ("summary", models.CharField(blank=True, max_length=300)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity", "entity_id"],
                        name="audit_activ_entity_b80d3b_idx",
                    ),
                    models.Index(
                        fields=["action"], name="audit_activ_action_259cfa_idx"
                    ),
                ],
            },
        ),
    ]
