# Generated by Django 5.0.6 on 2026-06-01 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DentalChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dentition",
                    models.CharField(
                        choices=[("ADULT", "Adult (32)"), ("CHILD", "Child (20)")],
                        default="ADULT",
                        max_length=6,
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dental_chart",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tooth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fdi_number", models.PositiveSmallIntegerField()),
                ("name", models.CharField(blank=True, max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("CARIES", "Caries"),
                            ("FILLING", "Filling"),
                            ("ROOT_CANAL", "Root Canal"),
                            ("CROWN", "Crown"),
                            ("BRIDGE", "Bridge"),
                            ("IMPLANT", "Implant"),
                            ("EXTRACTION", "Extraction"),
                            ("ORTHODONTIC", "Orthodontic Treatment"),
                        ],
                        default="HEALTHY",
                        max_length=12,
                    ),
                ),
                (
                    "chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teeth",
                        to="dental_charts.dentalchart",
                    ),
                ),
            ],
            options={
                "ordering": ["fdi_number"],
            },
        ),
        migrations.CreateModel(
            name="ToothCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("CARIES", "Caries"),
                            ("FILLING", "Filling"),
                            ("ROOT_CANAL", "Root Canal"),
                            ("CROWN", "Crown"),
                            ("BRIDGE", "Bridge"),
                            ("IMPLANT", "Implant"),
                            ("EXTRACTION", "Extraction"),
                            ("ORTHODONTIC", "Orthodontic Treatment"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "surface",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Mesial"),
                            ("D", "Distal"),
                            ("O", "Occlusal"),
                            ("B", "Buccal"),
                            ("L", "Lingual"),
                            ("", "Whole tooth"),
                        ],
                        max_length=1,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tooth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="dental_charts.tooth",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
