# Generated by Django 5.0.6 on 2026-06-01 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dental_charts", "0001_initial"),
        ("treatments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="toothcondition",
            name="treatment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tooth_conditions",
                to="treatments.treatment",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tooth",
            unique_together={("chart", "fdi_number")},
        ),
    ]
