# Generated by Django 5.0.6 on 2026-06-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="signature",
            field=models.ImageField(
                blank=True, null=True, upload_to="doctors/signatures/"
            ),
        ),
    ]
