# Generated by Django 5.0.6 on 2026-06-01 04:31

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("appointments", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("visit_date", models.DateField(default=datetime.date.today)),
                (
                    "visit_time",
                    models.TimeField(default=django.utils.timezone.localtime),
                ),
                ("chief_complaint", models.TextField(blank=True)),
                ("clinical_findings", models.TextField(blank=True)),
                ("diagnosis", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("queue_number", models.PositiveIntegerField(blank=True, null=True)),
                ("arrival_time", models.DateTimeField(blank=True, null=True)),
                (
                    "workflow_status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting"),
                            ("IN_CONSULTATION", "In Consultation"),
                            ("TREATMENT_IN_PROGRESS", "Treatment In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="WAITING",
                        max_length=24,
                    ),
                ),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visit",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visits",
                        to="accounts.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-visit_date", "queue_number"],
                "indexes": [
                    models.Index(
                        fields=["visit_date"], name="visits_visi_visit_d_61b894_idx"
                    ),
                    models.Index(
                        fields=["workflow_status"],
                        name="visits_visi_workflo_428d59_idx",
                    ),
                ],
            },
        ),
    ]
