# Generated by Django 5.0.6 on 2026-06-01 06:26

import apps.visits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="visit_time",
            field=models.TimeField(default=apps.visits.models.current_time),
        ),
    ]
