# Generated by Django 5.0.6 on 2026-06-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treatments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentplan",
            name="estimated_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
